export const users = [
  {
    key: "1",
    name: "Tony Reichert",
    isntructor: "CEO",
    totalLearner: 100,
  },
  {
    key: "2",
    name: "Zoey Lang",
    isntructor: "Technical Lead",
    totalLearner: 20,
  },
  {
    key: "3",
    name: "Jane Fisher",
    isntructor: "Senior Developer",
    totalLearner: 100,
  },
  {
    key: "4",
    name: "William Howard",
    isntructor: "Community Manager",
    totalLearner: 50,
  },
  {
    key: "5",
    name: "Emily Collins",
    isntructor: "Marketing Manager",
    totalLearner: 100,
  },
  {
    key: "6",
    name: "Brian Kim",
    isntructor: "Product Manager",
    totalLearner: 100,
  },
  {
    key: "7",
    name: "Laura Thompson",
    isntructor: "UX Designer",
    totalLearner: 100,
  },
  {
    key: "8",
    name: "Michael Stevens",
    isntructor: "Data Analyst",
    totalLearner: 20,
  },
  {
    key: "9",
    name: "Sophia Nguyen",
    isntructor: "Quality Assurance",
    totalLearner: 100,
  },
  {
    key: "10",
    name: "James Wilson",
    isntructor: "Front-end Developer",
    totalLearner: 50,
  },
  {
    key: "11",
    name: "Ava Johnson",
    isntructor: "Back-end Developer",
    totalLearner: 100,
  },
  {
    key: "12",
    name: "Isabella Smith",
    isntructor: "Graphic Designer",
    totalLearner: 100,
  },
  {
    key: "13",
    name: "Oliver Brown",
    isntructor: "Content Writer",
    totalLearner: 20,
  },
  {
    key: "14",
    name: "Lucas Jones",
    isntructor: "Project Manager",
    totalLearner: 100,
  },
  {
    key: "15",
    name: "Grace Davis",
    isntructor: "HR Manager",
    totalLearner: 100,
  },
  {
    key: "16",
    name: "Elijah Garcia",
    isntructor: "Network Administrator",
    totalLearner: 100,
  },
  {
    key: "17",
    name: "Emma Martinez",
    isntructor: "Accountant",
    totalLearner: 50,
  },
  {
    key: "18",
    name: "Benjamin Lee",
    isntructor: "Operations Manager",
    totalLearner: 100,
  },
  {
    key: "19",
    name: "Mia Hernandez",
    isntructor: "Sales Manager",
    totalLearner: 20,
  },
  {
    key: "20",
    name: "Daniel Lewis",
    isntructor: "DevOps Engineer",
    totalLearner: 100,
  },
  {
    key: "21",
    name: "Amelia Clark",
    isntructor: "Social Media Specialist",
    totalLearner: 100,
  },
  {
    key: "22",
    name: "Jackson Walker",
    isntructor: "Customer Support",
    totalLearner: 100,
  },
  {
    key: "23",
    name: "Henry Hall",
    isntructor: "Security Analyst",
    totalLearner: 100,
  },
  {
    key: "24",
    name: "Charlotte Young",
    isntructor: "PR Specialist",
    totalLearner: 20,
  },
  {
    key: "25",
    name: "Liam King",
    isntructor: "Mobile App Developer",
    totalLearner: 100,
  },
];
